# Generated by Django 5.0.1 on 2024-03-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_service_watch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="company",
            field=models.CharField(max_length=30, verbose_name="Empresa"),
        ),
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.EmailField(max_length=40, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="clients",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="clients",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="pendingservices",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="pendingservices",
            name="status",
            field=models.CharField(max_length=20, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="pendingservices",
            name="status_update_date",
            field=models.DateField(verbose_name="Fecha de actualización"),
        ),
        migrations.AlterField(
            model_name="servicesprovided",
            name="completed",
            field=models.BooleanField(blank=True, null=True, verbose_name="Entregado"),
        ),
        migrations.AlterField(
            model_name="servicesprovided",
            name="completion_date",
            field=models.DateField(verbose_name="Fecha de finalización"),
        ),
        migrations.AlterField(
            model_name="servicesprovided",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="email",
            field=models.EmailField(max_length=40, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Nombre"),
        ),
    ]
